fix typo in build-target.md
facebook/buck2 pull request #128
Opened 2023-04-08 17:30 UTC by eltociear

ommitted -> omitted

2023-04-08 17:33 UTC, stepancheg requested changes

2023-04-08 17:33 UTC, stepancheg commented on docs/legacy/concepts/build-target.md
> -```
Can you undo this change please?

2023-04-09 02:47 UTC, eltociear commented on docs/legacy/concepts/build-target.md
> -```
@stepancheg ok!

2023-04-09 02:51 UTC, eltociear commented on docs/legacy/concepts/build-target.md
> -```
fixed it!

2023-04-10 12:33 UTC, closed without merging